In [1]:
import logging
import numpy as np
import sys

from utils import svd_decomposition
from clements import decompose_clements

logging.basicConfig(
    stream=sys.stdout,      # Direct logs to stdout
    level=logging.DEBUG
)

### Input Matrix

In [2]:
A = np.array([
    [1.0,0.0,0.0,0.0],
    [0.0,1.0,0.0,0.0],
    [0.0,0.0,1.0,0.0],
    [0.0,0.0,0.0,1.0],
])
A = A.copy().astype(np.complex128)

### SVD Decomposition

In [3]:
U, S, Vt = svd_decomposition(A)

DEBUG:root:--- 1. Original Matrix A ---
DEBUG:root:[[1.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 1.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 1.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 1.+0.j]]
DEBUG:root:Input Matrix Shape: (4, 4)
DEBUG:root:--- 2. Decomposition Components ---
DEBUG:root:Matrix U (Left Singular Vectors):
DEBUG:root:[[1.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 1.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 1.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 1.+0.j]]
DEBUG:root:Shape: (4, 4)

DEBUG:root:Vector S (Singular Values):
DEBUG:root:[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
DEBUG:root:Shape: (4, 4)

DEBUG:root:Matrix Vt (Right Singular Vectors Transposed):
DEBUG:root:[[1.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 1.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 1.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 1.+0.j]]
DEBUG:root:Shape: (4, 4)



### Running Clement's Decomposition

In [6]:
U_c = decompose_clements(U)
Vt_c = decompose_clements(Vt)
S_c = decompose_clements(S)

In [7]:
U_c

(array([[3.14159265, 4.71238898],
        [3.14159265, 3.14159265],
        [4.71238898, 1.57079633]]),
 array([[1.57079633, 1.57079633],
        [1.57079633, 1.57079633],
        [1.57079633, 1.57079633]]),
 array([ 1.57079633e+00,  2.44929360e-16,  2.28847549e-17, -3.14159265e+00]))

In [8]:
Vt_c

(array([[3.14159265, 4.71238898],
        [3.14159265, 3.14159265],
        [4.71238898, 1.57079633]]),
 array([[1.57079633, 1.57079633],
        [1.57079633, 1.57079633],
        [1.57079633, 1.57079633]]),
 array([ 1.57079633e+00,  2.44929360e-16,  2.28847549e-17, -3.14159265e+00]))

In [9]:
S_c

(array([[3.14159265, 4.71238898],
        [3.14159265, 3.14159265],
        [4.71238898, 1.57079633]]),
 array([[1.57079633, 1.57079633],
        [1.57079633, 1.57079633],
        [1.57079633, 1.57079633]]),
 array([ 1.57079633e+00,  2.44929360e-16,  2.28847549e-17, -3.14159265e+00]))